name: CD

on:
  push:
    branches:
    - master

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pipenv
        key: pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --deploy

    - name: Build the metadata files
      run: pipenv run scripts/metadata_gen.py

    - name: Set up Git client
      run: |
        git config --local user.email "$GITHUB_ACTOR@$ACTOR_DOMAIN"
        git config --local user.name "$ACTOR_NAME"
      env:
        ACTOR_DOMAIN: users.noreply.github.com
        ACTOR_NAME: Dhruv Bhanushali

    - name: Commit and push to remote
      run: |
        git checkout --orphan deploy
        mv dist/metadata .
        git add .
        git commit -m "Deploy"
        git push --force origin deploy:metadata

